### ISSUE TITLE
ReadMe: Add Examples Showing how to make a get or post request!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [dadish/ProcessGraphQL#10]
i have no experience with GraphQL, but i know it's powerful - so i suggest you add an example shows how the developer can use this tech to send request and get data, and how the end point will look like.

**Comment by dadish** [comment]
Have you looked at the [demo video](https://www.youtube.com/watch?v=4M2VS5XAvts)? Or it is something else you're talking about?

**Comment by Mu9tafa-Online** [comment]
Yes i watched the video.. i mean something like this (I'm using jQuery here) : 

`$.ajax({
  url: "www.example.com/graphql/?????",
  context: document.body
}).done(function() {
  $( this ).addClass( "done" );
});`

** How the URL should look like ?

**Comment by dadish** [comment]
The URL is always the same. `https://example.com/graphql/`. That's one of the advantages of GraphQL. You don't need a separate url for each request. Everything is accessed from one URL. There is also only one HTTP method you should use. Which is `POST` method. No need for `GET`, `DELETE`, `PATCH` and etc.

The question you are asking is about how GraphQL works. Not how the module works. You can learn more about GraphQL at http://graphql.org

**Comment by Mu9tafa-Online** [comment]
Thanx for Clarification :)
