### ISSUE TITLE
Compability with Apollo

### ISSUE THREAD

**Issue by DaveDamage** [dadish/ProcessGraphQL#11]
Hi,

first of all let me thank you for ProcessGraphQL qhich has opened new possibilities with Processwire.

Ich have a Processwire Installation with ProcessGraphQL installed and use vuejs with vue-apollo. When I make a call to Graphql, the server responds with with the error message: »Must provide an operation.«.

I guess it has something to with how apollo - more specifically gql - sends the queries: 

`[{"query":"{ career { list { title id } }", "operationName":null}]`

So my question is, if I should catch the query before it is executed and then pass it or is there another solution?

Thank you very much

Dave

**Comment by dadish** [comment]
Is there any chance that your problem is related to #1 issue?

**Comment by hns-david** [comment]
I don't think so, I made sure I gave apollo the url with a trailing slash, but I will double-check this evening and apend a screenshot of the request.

**Comment by DaveDamage** [comment]
Here are the screenshots:

![apollo-screenie1](https://user-images.githubusercontent.com/10730207/31625115-364cc22e-b2a5-11e7-9a1c-2c842e93a21f.png)
![apollo-screenie2](https://user-images.githubusercontent.com/10730207/31625117-366e010a-b2a5-11e7-88b0-a0b4f3a9a7dc.png)

**Comment by dadish** [comment]
The `Must provide an operation.` error happens when no query is received by the GraphQL library. Let's find out if that is the case. In your template, where you execute ProcessGraphQL, do
```php
<?php namespace ProcessWire;

die('JSON payload is: ' . file_get_contents('php://input'));

echo $modules->get('ProcessGraphQL')->executeGraphQL();
```
Make a request and then look at the response. This must show us if the JSON payload actually reaches the module.

**Comment by DaveDamage** [comment]
Looks like the payload arrives:

![apollo-screenie3](https://user-images.githubusercontent.com/10730207/31625980-5494d822-b2a8-11e7-9605-e4d2da79bcf7.png)

**Comment by dadish** [comment]
Sorry, but I realized just now that you are sending an array of queries, instead of one. Which currently is not supported. You need to send one query operation. So instead of 
```
[{ career { list { title __typename } __typename } }]
```
you should send
```
{ career { list { title __typename } __typename } }
```

**Comment by DaveDamage** [comment]
I feared as much and will fix it. Thank you for your time.
