### ISSUE TITLE
graphiql with multilanguage processwire setup

### ISSUE THREAD

**Issue by tiefenb** [dadish/ProcessGraphQL#14]
I have a multilanguage website and when I'm accessing /de/graphiql/ the request goes always to the fallback language endpiont (english): /en/graphql/

![graphiql](https://user-images.githubusercontent.com/488163/32484570-9a418c22-c3a0-11e7-8077-596e7c007125.png)

**Comment by dadish** [comment]
GraphQL is designed to have only one endpoint. It does not matter where that is. If you want requests to go `/de/graphql` you can do so with the api. Please refer to https://github.com/dadish/ProcessGraphQL#graphiql-endpoint documentation on how you can set exact endpoint for graphql server.

**Comment by tiefenb** [comment]
Then how can I define which language will be in the result?

**Comment by dadish** [comment]
Please refer to https://processwire.com/talk/topic/15397-graphql-for-processwire/?page=2&tab=comments#comment-138925

**Comment by tiefenb** [comment]
ok thx!
