### ISSUE TITLE
logout() return warning in response header

### ISSUE THREAD

**Issue by smbdelse** [dadish/ProcessGraphQL#16]
This issue was already posted on main ProcessWire channel, but I thought it would be good to signal it's existence here too.

Full description of the problem can be found [here](https://github.com/processwire/processwire-issues/issues/497)

**Comment by dadish** [comment]
Hey @smbdelse 
Can you confirm that logout does not work in GraphiQL in the ProcessWire admin? What happens when you run the following query on GraphiQL?
```
{
  logout {
    message
  }
}
```

If that works fine, please show the request/response exchange of the logout call between your Apollo client and GraphQL api.

**Comment by smbdelse** [comment]
Ok, I think that I finally tracked down where the problem comes from (it's still a bit of "I don't know what the heck I'm doing", but well... it works)

When constructing ApolloClient I have added optional header

```
const apolloClient = new ApolloClient({
  link: httpLink,
  cache: new InMemoryCache(),
  connectToDevTools: true,
  opts: {
    headers: {
      "X-Requested-With": "XMLHttpRequest",
    }
  }
})
```

And It finally works perfectly! Thank you for pointing me to check for differences between requests in GraphiQL and Apollo, this is how I got to this :) 

So, now my only problem is that sessions are cookie-based so it's hard to make it truly headless. I was wondering about including somehow JWT, but I don't know if I could handle that.

**Comment by dadish** [comment]
@smbdelse  Supporting JWT for sessions is more related on how the ProcessWire sessions works. Not related to this module. My suggestions would be to use hooks and modify the behavior of the `$session` api variable and make the use of JWT under the hood.

Here how it might look like
```php
wire()->addHookAfter('Session::loginSuccess', function($event) {
  // set your JWT headers here
});

wire()->addHookAfter('Session::logoutSuccess', function($event) {
  // remove your JWT headers here
});
```

I'm gonna close this issue, but if you have any further questions feel free to reopen it.
