### ISSUE TITLE
Repeater

### ISSUE THREAD

**Issue by LudwigBogner** [dadish/ProcessGraphQL#17]
Hello,

Are repeater fields supposed to work with this module? So far I've tried using a repeater and matrix repeater but I get the error message that the "Field "repeater" not found in type "ObjectPage".

Thanks

**Comment by LudwigBogner** [comment]
Ah I missed the point about third party fields in the readme

**Comment by Arcath** [comment]
@LudwigBogner did you find/create a module that solved this?

**Comment by LudwigBogner** [comment]
@Arcath no I gave up in the end and went back to using a rest api...
