### ISSUE TITLE
How to enable CORS?

### ISSUE THREAD

**Issue by eliasleyton** [dadish/ProcessGraphQL#20]
I trie to use this module for my API. But from Vue or apollo client, I have the following error: 

` – "Network error: Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin."`

How I Can enable cors to Apollo Server Module?

**Comment by MrSnoozles** [comment]
This has nothing to do with Apollo Server. You can allow CORS for example with an htaccess directive:
https://stackoverflow.com/a/20838470

**Comment by eliasleyton** [comment]
@MrSnoozles thanks
