### ISSUE TITLE
Error: Schema must contain unique named types!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [dadish/ProcessGraphQL#22]
![Annotation 2019-09-16 131111](https://user-images.githubusercontent.com/5323832/64953664-a90c9400-d883-11e9-965b-7a49cd1eb60f.jpg)

**PHP**: 7.2 - **PW**: v3.0.139

{
  "error": true,
  "message": "Schema must contain unique named types but contains multiple types named \"Page\" (see http://webonyx.github.io/graphql-php/type-system/#type-registry)."
}

**Comment by dadish** [comment]
Is there anyway to reproduce this? Any steps? Can you reproduce this in any of the default ProcessWire profiles?

**Comment by Mu9tafa-Online** [comment]
Yup, works fine on a fresh installation. Sorry my bad :(

**Comment by Mu9tafa-Online** [comment]
I tried it on many running websites, same error!
.
I Don't know what is going on

**Comment by dadish** [comment]
It should work on any pw installation. If it doesn't work for you then there is some bug. Can you share those websites that you tried and didn't work? If you could export the site with [Profile Exporter](http://modules.processwire.com/modules/process-export-profile/) and I could reproduce it on my machine then I could fix it.

I suppose those sites are private. That's why I asked if you could reproduce the error in one of the publicly available profiles.

**Comment by Mu9tafa-Online** [comment]
@dadish Yes All Of them are private, i will try to do my best.

**Comment by Mu9tafa-Online** [comment]
@dadish - I need your **Email**, so i can send you the site profile i have.

**Comment by dadish** [comment]
nurguly.ashyrov@gmail.com

**Comment by dadish** [comment]
I was able to reproduce the bug with http://modules.processwire.com/modules/editorial-responsive-blog-profile/

You don't need to send me your site profile.

**Comment by Mu9tafa-Online** [comment]
Done, Check Your Email!

**Comment by Mu9tafa-Online** [comment]
Any Updates ?

**Comment by dadish** [comment]
Still working on it. I'm doing some refactoring along the way. Give me couple days and I will git it done.

**Comment by Mu9tafa-Online** [comment]
@dadish , Many Thanks.
I'm wondering if this new release supports "**Repeater / Matrix**" Fields ?

**Comment by dadish** [comment]
Not yet. Repeater fields are coming next, you can track it's progress at issue #19. Matrix fields will not be supported directly by ProcessGraphQL because it's a third-party fieldtype. Matrix could be supported by another third-party module.

**Comment by dadish** [comment]
@Mu9tafa-Online  I made some updates. Please check the [latest tag](https://github.com/dadish/ProcessGraphQL/releases/tag/v1.0.0-rc16) and let me know if it works for you.

**Comment by Mu9tafa-Online** [comment]
Yup, no errors - You are super awesome.
.
Just one thing: **title** field doesn't appear in filed list (on GraphiQL Page) in-spite it's checked in Legal fields.

**Comment by Mu9tafa-Online** [comment]
Yeaaah, It's fine until now, just one little thing:
I can't access **title** Field using GraphiQL ! it doesn't show.

(Note: Errors Appears Again when I checked on Repeater Fields )

**Comment by dadish** [comment]
Can't reproduce the **title** error. If I check it on the module settings it works.
Request:
```graphql
{
  blog_post{
    list{
      title
    }
  }
}
```
Response:
```json
{
  "data": {
    "blog_post": {
      "list": [
        {
          "title": "Example Post"
        },
        {
          "title": "Post 2"
        },
        {
          "title": "Post number three"
        },
        {
          "title": "Post 4"
        },
        {
          "title": "Post number five"
        }
      ]
    }
  }
}
```
Tested this on [Editorial Responsive Blog Profile](http://modules.processwire.com/modules/editorial-responsive-blog-profile/)

Can you reproduce the error with this profile? Sorry I deleted the site profile you sent me earlier. And I can't download it again for some reason.

**Comment by Mu9tafa-Online** [comment]
I had to revert back to old version (v0.23.5) .. my project's deadline is tomorrow,
so maybe next week i find time to test more.
You are doing a great job, I'm super happy with this module.

**Comment by dadish** [comment]
Hello @Mu9tafa-Online. I just released the [latest version](https://github.com/dadish/ProcessGraphQL/releases/tag/v1.0.2) with lots of updates since last time. Check it out when you have time and let me know if your issue is resolved.

**Comment by Mu9tafa-Online** [comment]
@dadish The new version works just fine, 
But the **Title** isse still exists .
![Title](https://user-images.githubusercontent.com/5323832/69330606-e7e01100-0c5b-11ea-8208-7a3b376a0fab.PNG)

**One more thing: can you load these files locally instead of cdn?**

![asssssets](https://user-images.githubusercontent.com/5323832/69330792-486f4e00-0c5c-11ea-89d0-ec05af7b298d.PNG)

**Comment by dadish** [comment]
Did you add `title` field in the module configuration? Are you making this request as a superuser? Did you login before making this request? If not superuser, then did you grant access to view this field to the user you are using to request?

Try below request to see what user is logged in
```graphql
{
  me {
    name
  }
}
```


> can you load these files locally instead of cdn?

What's wrong with loading scripts from cdn?

**Comment by Mu9tafa-Online** [comment]
Yup I'm logged-in as a **superuser**, and yes I added **title** field in the module configuration.

(nothing wrong with loading scripts from CDN, but i prefer to work offline when in a local environment)

**Comment by dadish** [comment]
> Yup I'm logged-in as a superuser, and yes I added title field in the module configuration.

Hmmm, tough. Can't understand how this might be happening. You need to help me here. Could you please reproduce this in any of the [public profiles](http://modules.processwire.com/categories/site-profile/) and export it? I can't fix the bug if I can't reproduce it.

> (nothing wrong with loading scripts from CDN, but i prefer to work offline when in a local environment)

Didn't anticipate it would be an issue. Loading those file from CDN allows us to remove all js dependencies and simplifies the build process. I hope you don't mind I leave it like that for now. I will reconsider if there will be more people complaining about it.

**Comment by Mu9tafa-Online** [comment]
works fine on a fresh installation (but not on existing one), maybe close the issue for now.
