### ISSUE TITLE
Unexpected EOF error when calling the endpoint 

### ISSUE THREAD

**Issue by dsdsdsdsdsds** [dadish/ProcessGraphQL#23]
I installed module version 1.0.016 and used the `Generate` button in the module settings to install the corresponding ProcessWire templates and pages. I’m now running into the following error when calling the GraphQL endpoint under `graphql/`:

```
{"errors":[{"message":"Syntax Error: Unexpected \u003CEOF\u003E","extensions":{"category":"graphql"},"locations":[{"line":1,"column":1}]}]}
```
The Graph*i*QL interface works flawlessly however. Writing queries in there leads to the expected response.

**Comment by dsdsdsdsdsds** [comment]
Sorry, my bad. I was missing the trailing slash when defining the GraphQL endpoint in my client app. I found the hint to that somewhere in the support forum. Maybe a small note in the docs would be helpful. Thanks!

**Comment by jonasvonarb** [comment]
Hei I know that was a long time ago, but I am running in to the same problem here. I did try to add a trailing slash but It did not change. Do you remember, what you did exactly?

**Comment by MochiGroupNet** [comment]
We were having the same, issue, for us if you use a system such as Magento with ssl termination you would use this as a common graphql query method.

      `$secure = ($ssl) ? 'ssl' : 'http';
      if (false === $data = @file_get_contents($endpoint, false, stream_context_create([
        $secure => [
            'method' => 'POST',
            'header' => $headers,
            'content' => json_encode(['query' => $queryfull, 'variables' => $variables]),
        ]
      ]))) {
        $error = error_get_last();
        throw new \ErrorException($error['message'], $error['type']);
      }`

With Pimcore it appears the ssl method is not available, even though it uses ssl for the connection, so we changed it to after half a day debugging, now no "Unexpected \u003CEOF\u003E" error.

      `$secure = ($ssl && $mage) ? 'ssl' : 'http';
      if (false === $data = @file_get_contents($endpoint, false, stream_context_create([
        $secure => [
            'method' => 'POST',
            'header' => $headers,
            'content' => json_encode(['query' => $queryfull, 'variables' => $variables]),
        ]
      ]))) {
        $error = error_get_last();
        throw new \ErrorException($error['message'], $error['type']);
      }`
