### ISSUE TITLE
PageClass in page creation

### ISSUE THREAD

**Issue by sebastiandittrich** [dadish/ProcessGraphQL#29]
When creating a page using the GraphQL Endpoint, the class defined in `$template->pageClass` is not used instead of the default `ProcessWire\Page` class. This can cause issues if you rely on the correct page class for further processing of the page, for example in `beforeSave` Hooks.

The code where this should be implemented is here: 
https://github.com/dadish/ProcessGraphQL/blob/2b28b6914dba6416f2e6c2506c882f2a1f2e56cf/src/Field/Mutation/CreatePage.php#L111

**Comment by dadish** [comment]
Should be pretty straightforward to implement. Most work will be related to creating a good test cases. Will have to create custom pages for this in the db. Will try to resolve this this weekend.

**Comment by dadish** [comment]
@sebastiandittrich Please close if this is fixed.
