### ISSUE TITLE
Empty results

### ISSUE THREAD

**Issue by MartinMuzatko** [dadish/ProcessGraphQL#4]
Hello!

I don't get any results when querying for a template list like the following:

```graphql
{
    page {
        list {
            id
        }
    }
}
```
Is there anything else I have to set up for it to work? The pages using the template `page` are all public facing and there should be no problem in the setup.

![image](https://cloud.githubusercontent.com/assets/2950505/26589276/e4cb19d8-4557-11e7-972f-69c720f21e2c.png)

Thank you in advance.

**Comment by dadish** [comment]
That's a very odd one. Need little more context. Is there any errors in the browser console or in server side? Are you sure there are pages in your app with template `page`? 
Also could you make a following query.
```
{
  page {
    getTotal
    list {
      id
    }
  }
}
```

**Comment by MartinMuzatko** [comment]
Hello @dadish - thank you for your time!

I have plenty of pages: 
![image](https://cloud.githubusercontent.com/assets/2950505/26630597/b9e2f05a-4607-11e7-9db7-7b9ea53ff760.png)

And no. No errors in console. The XHR call already reports 0 entries.

![image](https://cloud.githubusercontent.com/assets/2950505/26630640/e499d098-4607-11e7-927f-73429bdff54f.png)

I'm running ProcessWire 3.0.59

**Comment by dadish** [comment]
@MartinMuzatko there was lots changes/improvements since this issue started. Can you confirm that issue is still present for you? Please install the latest version from [here](http://github.com/dadish/processgraphql/releases).

**Comment by dadish** [comment]
I'm closing this issue because it has not been active for a while. Please open it back if issue is still present.

**Comment by MartinMuzatko** [comment]
I have now upgraded to latest PW and ProcessGraphQL and everything is working great..
Thank you @dadish !
