### ISSUE TITLE
Cannot query field "pages" on type "Query"

### ISSUE THREAD

**Issue by timohausmann** [dadish/ProcessGraphQL#51]
Hi, I'm trying to find a page by url and saw the [experimental pages](https://github.com/dadish/ProcessGraphQL/blob/main/ScreenCast.md) to fetch any page. But I get the GraphQL error: _Cannot query field "pages" on type "Query"_. This would be really helpful to use. 

```
{
  pages {
    find(s:"name=home") {
      list {
        id
        name
      }
    }
  }
}
```

I'm not sure if I'm on 1.4 or 1.3.0, before install it says 1.4 but then when installed 1.3.0 (installed by PW Module Name). 

I tried to install via ZIP URL, but both 1.3.2 and 1.4 **ProcessWire module (ZIP)** Releases give me this error: _Failed opening required '/site/modules/ProcessGraphQL/vendor/composer/autoload_real.php'_ (this path does not exist in the ZIP).

**Comment by dadish** [comment]
@timohausmann  Sorry for all these unrelated comments.

The `pages` field was deprecated a while back ago.

Regarding the error `Failed opening required '/site/modules/ProcessGraphQL/vendor/composer/autoload_real.php' ` it is fixed with the latest release.
