### ISSUE TITLE
Query error

### ISSUE THREAD

**Issue by mauphung** [dadish/ProcessGraphQL#70]
I got the query error for following query:
{
  skyscraper{
    list {
      title
    }
  }
}
The error is:
Variables are invalid JSON: Expected property name or '}' in JSON at position 4.
Would you please give me some hints.![image](https://user-images.githubusercontent.com/361091/212549794-dad61b97-2c7d-4e53-97fe-e4be7fd1d7de.png)

**Comment by MrSnoozles** [comment]
You are putting your `query` into the inputfield for `query variables`.

![grafik](https://user-images.githubusercontent.com/17496592/218815711-33657c8f-8431-4147-aecf-99272d3f0f28.png)


Try if you can move the `Query variables  / Request Headers` panel down.


![query-variables](https://user-images.githubusercontent.com/17496592/218816252-e42d13ad-0f8b-479c-9b18-a506627209ce.gif)

**Comment by dadish** [comment]
@mauphung Please close the issue if the issue is resolved for you.
